version: '3.6'

services:
  database:
    image: mysql
    restart: always
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: user_db
      MYSQL_ROOT_PASSWORD: root