version: '3.6'

services:
  database:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql # For Development data retention.
      - ./migration:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: user_db
      MYSQL_ROOT_PASSWORD: root