// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-05-26 13:53:29.363967224 +0700 +07 m=+0.040199826

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "This is a sample server User-service.",
        "title": "Swagger Example API",
        "contact": {
            "name": "Son Luong Ngoc",
            "url": "https://sluongng.gitlab.io/",
            "email": "sluongng@gmail.com"
        },
        "license": {},
        "version": "1.0"
    },
    "paths": {
        "/user": {
            "post": {
                "description": "Create new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Creating new user",
                "parameters": [
                    {
                        "description": "user info",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.NewUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.User"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.NewUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "sluongng@gmail.com"
                },
                "name": {
                    "type": "string",
                    "example": "Son Luong"
                },
                "website": {
                    "type": "string",
                    "example": "https://sluongng@gmail.com"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "sluongng@gmail.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Son Luong"
                },
                "website": {
                    "type": "string",
                    "example": "https://sluongng@gmail.com"
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
